title: BioNeMo Demo
description: Demo and tips for BioNeMo Framework and API
theme: just-the-docs

url: https://xinyu-dev.github.io/bionemo-demo

aux_links:
  Template Repository: https://github.com/xinyu-dev/bionemo-demo


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"