title: BioNeMo Demo
description: Demo and tips for BioNeMo Framework and API
theme: just-the-docs

url: https://xinyu-dev.github.io/bionemo-demo

aux_links:
  Template Repository: https://github.com/xinyu-dev/bionemo-demo

plugins:
  - jekyll-default-layout
